### ISSUE TITLE
Endpoint myStatement

### ISSUE THREAD

**Issue by smiqueias** [somosphi/desafio-android#14]
Olá devs,

Eu estava utilizando este teste para consolidar meus estudos mas não estou conseguindo acessar o endpoint do myStatement. O do myBalance funciona perfeitamente.

Queria saber se não existe a possibilidade de vocês disponibilizarem novamente o acesso a este endpoint para que eu e outros desenvolvedores que encontrarem esse teste possam implementa-lo por completo.

**Comment by thiaguh11** [comment]
Olá @smiqueias, tbm estou pensando em utilizar esse desafio para estudo, pelo que entendi nesse endpoint de consulta do statement vc deve obrigatoriamente passar os valores para os router params limit e offset, desta forma:
https://desafio-mobile-bff.herokuapp.com/myStatement/1/1
